### ISSUE TITLE
"Error: Module name "lib/gpxfile" has not been loaded yet for context: _. Use require([])

### ISSUE THREAD

**Issue by Alex-ej** [kchapelier/gpx#1]
Hi,

so I'm trying to use this library, but when I try to load index.js after having loaded require.js into my project, I get the error: 
"Error: Module name "lib/gpxfile" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded"

I have tried to implement the recommended solution on the above mentioned website, but it does not work. 

Do you have any solutions for that?

**Comment by kchapelier** [comment]
Hi,

This library was originally designed to be used in a CommonJS environment and thus is not directly compatible with RequireJS which is an AMD environment.

I pushed an UMD build here : https://github.com/kchapelier/gpx/blob/master/build/gpx.js it should work just fine with RequireJS.

Please, take notice that this library was a work in progress for a professional project which ended up going another direction. It 'works' but is not properly battle-tested or documented.
